```js
function test(title, callback) {
  
}
```
because the callback could throw and error, wrap it in try-catch
```js
function test(title, callback) {
  try {
    callback()
  } catch (error) {
    console.error(error)
  }
}
```
and because we want the test result to be helpful

```js
function test(title, callback) {
  try {
    callback()
    console.log(`✓ ${title}`)
  } catch (error) {
    console.error(`✕ ${title}`)
    console.error(error)
  }
}
```

can now be called as 
```js
test(`sum adds numbers`, () => {
  const result = sum(3, 7)
  const expected = 10
  expect(result).toBe(expected);
});

test(`subtract subtracts numbers`, () => {
  const result = sum(7, 3)
  const expected = 4
  expect(result).toBe(expected);
})
```